name: Deploy Vue Dev
on: 
  push:
    branches:
      - feature/*
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          with:
            ref: ${{ github.ref }}